name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - name: Install JS dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Commit and push distified version to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update distified version'
          file_pattern: 'dist/index.js'
